const des = {
    0:"You wake up in pitch black darkness. After your eyes begin to adjust you make out very faintly that you are in a cave of some sort, whilst also noticing you are heavily injured and bleeding. You see a very faint light in the darkness ahead",
    1:"You can faintly make out a doorway, and upon reaching it notice a glass window letting in some moonlight as well as two doors. The inside of the left door is dark and foreboding and the right door is dimly lit with vegetation growing aroud it.",
    2:"You reach the window and see that you are on the second floor of a grand castle looking building, and that the dim light illuminating the room is shining from the full moon above you in the sky. Whilst looking, you hear a loud crash reverberate through the left door.",
    3:"test",
    4:"test",
    5:"test",
    6:"test",
    7:"test",
    8:"test",
    9:"test",
    10:"test",
    11:"test",
    12:"test",
    13:"test",
    14:"test",
    15:"test",
    16:"test",
    17:"test",
    18:"test",
    19:"test",
    20: "test",
    
}